---
apiVersion: batch/v1
kind: Job
metadata:
  name: "add-default-user"
  namespace: {{ .Values.namespace }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    checksum/configMap: {{ include (print $.Template.BasePath "/0-configmap.yaml") . | sha256sum }}
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
    spec:
      restartPolicy: Never
      containers:
      - name: scripts
        image: "appropriate/curl:latest"
        command: ["/bin/sh","-c"]
        args: ["cp ./scripts/*.sh / && chmod +x /add_user.sh && /add_user.sh"]
        volumeMounts:
        - mountPath: /scripts/
          name: scripts
      volumes:
      - configMap:
          name: scripts
        name: scripts
      restartPolicy: OnFailure
