apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-{{.Values.namespace}}-backend-mariadb-master-0
  namespace: {{.Values.namespace}}
  annotations:
    snapshot.alpha.kubernetes.io/snapshot: snapshot-mariadb-{{.Values.backupDate}}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 9Gi
  storageClassName: snapshot-promoter
